SteamDeckHomebrew/decky-frontend-lib

- src/deck-components/Router.tsx
Adds the ability to get the main running app and to navigate to the running app
> feat(Router.tsx): adds more methods to router

- src/deck-components/Router.tsx
Haven't found much there that could be otherwise useful
> fix(Router): Add more members to Router interface

- src/deck-components/TextField.tsx
> fix(TextFieldProps): Add "disabled" option to TextFieldProps

- src/utils.ts
> fix(utils): update wrapReactClass impl. and defaults for prop argument

- src/deck-components/static-classes.ts
- src/utils.ts
> Add necessary stuff to properly patch into play section

- src/utils.ts
Sorry @AAGaming00  was late by a few seconds to fix this :'(
> fix(utils): Mutable variable must be non-const

- src/plugin.tsx
https://github.com/SteamDeckHomebrew/decky-loader/pull/151 :)
> Export ServerResponse for use in my PR

- src/deck-components/Field.tsx
- src/deck-components/Item.tsx
> Fix Field and Item types

- src/deck-components/SidebarNavigation.tsx
`page` & `onPageRequested` in conjunction with `identifier` can be used to make the navigation controllable.
> fix(SidebarNavigation): add more props

- src/deck-components/Button.tsx
- src/deck-components/Dialog.tsx
- src/deck-components/index.ts
> Add dialog components

- src/deck-components/Modal.tsx
> fix(modal): make children optional

- src/deck-components/Menu.tsx
missed these the first time around
> feat(Menu): add more missing props

- src/deck-components/Router.tsx
Navigation is an aggregator for the depths of hell that Valve has moved the Router functions to.
> fix(Router): update Router interface to SteamOS3.4 and add Navigation

- src/deck-components/Modal.tsx
valve don't rewrite the modals every single update challenge (impossible)
needs testing on all SteamOS branches
> fix(modals): fix ModalRoot again

- src/deck-components/Panel.tsx
> fix: fixed prop interfaces

- pnpm-lock.yaml
- src/custom-components/ReorderableList.tsx
Reorderable list now saves when the user unfocuses the list. Should help cover a bunch of edge cases
> Add save on backout to reorderable list component.

- src/deck-components/Menu.tsx
- src/deck-components/static-classes.ts
Thanks to AAGaming and McDjuady for fixing this stuff.
> fix(decky): fix decky on latest beta

- src/deck-components/static-classes.ts
- src/utils/index.ts
Required for [this PR](https://github.com/SteamDeckHomebrew/decky-loader/pull/458)
> Gamepad UI classes, fix findSP to return null when not found

- src/custom-hooks/useQuickAccessVisible.tsx
Focus/blur events are not emitted when a dropdown menu window pops up and then "vanishes" (pops down?!). The "Page Visibility API" works in such case and the other cases covered by focus/blur.
When I implemented this hook, either my testing was flawed for "Page Visibility API" or it didn't work properly at the time, but now it's more reliable than focus/blur events.
> fix(useQuickAccessVisible): use the "Page Visibility API" instead of focus/blur

- src/deck-components/static-classes.ts
> feat(static-classes): add more css classes

- src/components/FooterLegend.ts
Add missing props regarding navigation/focus with some detailed explanations.
> fix(Footer): add missing focus/nav properties
